Add version command

diff --git a/tidbit b/tidbit
--- a/tidbit
+++ b/tidbit
@@ -6,6 +6,7 @@
 # --- --- #
 
 # --- Variables --- #
+VERSION=1.0.0
 script_dir="$(cd "$(dirname "$0")" && pwd)"
 # --- --- #
 
@@ -35,10 +36,25 @@ handle_help() {
     esac
 }
 
+handle_version() {
+    arg1=$(printf '%s' "$1" | tr '[:upper:]' '[:lower:]')
+    case "${arg1}" in
+        -v|--v|--version|version)
+            printf "tidbit version %s\n" "$VERSION"
+            exit 0
+            ;;
+    esac
+}
+
 handle_config_edit() {
     if [[ "$#" -eq 1 && "$1" == "config" ]]; then
-        "$editor" "$script_dir/.tidbitconfig"
-        exit 0
+        if [ -f "$script_dir/.tidbitconfig" ]; then
+            "$editor" "$script_dir/.tidbitconfig"
+            exit 0
+        else
+            printf "error: %s/.tidbitconfig not found\n" "$script_dir"
+            exit 1
+        fi
     fi
 }
 
@@ -56,6 +72,7 @@ main() {
     load_config
     validate_arg_count "$@"
     handle_help "$1"
+    handle_version "$1"
     handle_config_edit "$@"
 
     if [ -n "$1" ]; then
